version: 2

project_name: gridbeat

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/fluxionwatt/gridbeat/version.Version={{ .Version }} -X github.com/fluxionwatt/gridbeat/version.CommitSHA={{ .ShortCommit }}
    main: main.go
    binary: gridbeat
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "amd64"
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: "arm64"
archives:
  - name_template: "{{ .ProjectName }}-{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - none*
      - config/*.yaml

nfpms:
  - id: rpm
    package_name: gridbeat
    file_name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{- if eq .Arch "amd64" -}}x86_64{{- else if eq .Arch "arm64" -}}aarch64{{- else -}}{{ .Arch }}{{- end -}}
    homepage: https://www.fluxionwatt.com
    maintainer: "fluxionwatt Team <opentruenvr@gmail.com>"
    description: "GridBeat industrial gateway & energy orchestration service."
    license: Apache-2.0
    formats:
      - rpm
      - deb
    dependencies:
      - logrotate
    bindir: /usr/sbin
    scripts:
      postinstall: packaging/postinstall.sh
      preremove: packaging/preremove.sh
    contents:
      - src: "./packaging/cron.daily"
        dst: "/etc/cron.daily/gridbeat"
      - src: "./packaging/systemd"
        dst: "/usr/lib/systemd/system/gridbeat.service"
      - src: "./packaging/logrotate"
        dst: "/etc/logrotate.d/gridbeat"
      - src: "./packaging/default"
        dst: "/etc/sysconfig/gridbeat"
      - src: "./config/gridbeat-nfpm.yaml"
        dst: "/etc/gridbeat/gridbeat.yaml"
        type: config
      - dst: /var/lib/gridbeat
        type: dir
        file_info:
          mode: 0755
          owner: root
          group: root
      - dst: /var/log/gridbeat
        type: dir
        file_info:
          mode: 0755
          owner: root
          group: root
      - dst: /var/lib/gridbeat/data
        type: dir
        file_info:
          mode: 0755
          owner: root
          group: root
      - dst: /var/lib/gridbeat/extra
        type: dir
        file_info:
          mode: 0755
          owner: root
          group: root
