version: '3'

vars:
  SITE_DOCKER_FLAGS: >-
    -v ./www:/docs
    -v ./LICENSE:/docs/docs/LICENSE
    -v ./SECURITY.md:/docs/docs/security.md
    -v ./CHANGELOG.md:/docs/docs/changelog.md
    -v ./CODE-OF-CONDUCT.md:/docs/docs/code-of-conduct.md
    -v ./CONTRIBUTING.md:/docs/docs/contributing.md

tasks:
  build:frontend:
    desc: Build frontend assets
    dir: frontend
    cmds:
      - npm install
      - npm run build

  build:backend:
    desc: Build backend binary
    env:
      CGO_ENABLED: '1'
      GO111MODULE: 'on'
    cmds:
      - |
        set -e
        for d in ./plugins/*; do
          if [ -d "$d" ]; then
            name=$(basename "$d")
            echo "==> building plugin $name"
            go build -buildmode=plugin -o "plugins/${name}.so" "./plugins/${name}"
          fi
        done
      - go build -ldflags='-s -w -X "github.com/fluxionwatt/gridbeat/version.Version={{.VERSION}}" -X "github.com/fluxionwatt/gridbeat/version.BUILDTIME={{.BUILD_TIME}}" -X "github.com/fluxionwatt/gridbeat/version.CommitSHA={{.GIT_COMMIT}}"' -o gridbeat .
    vars:
      BUILD_TIME:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
      VERSION:
        sh: git describe --tags --abbrev=0 --match=v* | cut -c 2-

  build:
    desc: Build both frontend and backend
    cmds:
      - task: build:frontend
      - task: build:backend

  pub:
    desc: Publish site to GitHub Pages
    cmds:
      - echo
